export const mockPayments: Payment[] = [
  {
    id: 1,
    client_id: 1,
    client_name: "Trinidad Reyes",
    appointment_id: 1,
    service_summary: "Haircut + Color",
    amount: 1400,
    method: "cash",
    status: "paid",
    notes: null,
    paid_at: daysAgo(0, 10, 30),
  },
  {
    id: 2,
    client_id: 2,
    client_name: "Carlo Dizon",
    appointment_id: 2,
    service_summary: "Manicure",
    amount: 350,
    method: "gcash",
    status: "paid",
    notes: null,
    paid_at: daysAgo(1, 14, 0),
  },
  {
    id: 3,
    client_id: 3,
    client_name: "Beth Ramos",
    appointment_id: 3,
    service_summary: "Haircut",
    amount: 200,
    method: "card",
    status: "paid",
    notes: null,
    paid_at: daysAgo(1, 9, 15),
  },
  {
    id: 4,
    client_id: 4,
    client_name: "Ana Villar",
    appointment_id: 4,
    service_summary: "Color",
    amount: 1200,
    method: "cash",
    status: "paid",
    notes: null,
    paid_at: daysAgo(3, 16, 45),
  },
];